//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtividadePW2_Relacionamento1_N.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmprestimo
    {
        public int Id_Emprestimo { get; set; }
        public int Id_Livro { get; set; }
        public string DataEmprestimo { get; set; }
        public string DataDevolucao { get; set; }
    
        public virtual tblLivro tblLivro { get; set; }
    }
}
